#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d I II III IV V VI VII 
bspc monitor HDMI-A-0 -d VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a "Gnome-terminal" desktop=^'1' follow=on
bspc rule -a "Firefox" desktop=^'2' follow=on
bspc rule -a "Google-chrome" desktop=^'3' follow=on
bspc rule -a "albert" follow=on focus=on

##  Examples
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

albert &
feh --bg-fill $HOME/Imágenes/BG.jpg &
bash $HOME/.config/polybar/launch.sh &
bspc config border_width 0 &
picom --experimental-backends &
xsetroot -cursor_name left_ptr
