#! /bin/sh

wmname LG3D &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP -d I II III IV V VI  
bspc monitor HDMI-A-0 -d VII VIII IX X

#bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true

bspc rule -a "Gnome-terminal" desktop=^'1' follow=on
bspc rule -a "Firefox" desktop=^'2' follow=on
bspc rule -a "Brave-browser" desktop=^'2' follow=on
bspc rule -a "Google-chrome" desktop=^'3' follow=on
bspc rule -a "albert" follow=on focus=on

##  Examples
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

albert & #Lanza el launcher apps albert 
rofi & #Lanza el launcher rofi 
feh --bg-fill $HOME/Imágenes/BG.jpg & # Pone el fondo de pantalla
bash $HOME/.config/polybar/launch.sh & # Pone las polybar 
bspc config border_width 0 & # Quita los bordes 
picom --experimental-backends & # Pone los bordes redondeados 
xsetroot -cursor_name left_ptr # Pone el cursor
